/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package br.univali.ttoproject.compiler.parser;

public class Parser implements ParserConstants {
    public String errorMessages = "";

  final public void Start() throws ParseException {
    Program();
    jj_consume_token(0);
}

  final public void Program() throws ParseException {
    HeaderSel();
    T(PROGRAM);
    T(LBRACE);
    Define();
    Execute();
    T(RBRACE);
    IdentifierSel();
}

  void T(int tk) throws ParseException {token = getNextToken();
    System.out.println("cur tk: " + token.image + " " + token.kind);
    while (token.kind != tk && token != null && token.kind != EOF ){
        errorMessages += "Deu merda! " + token.image + " \n";

        System.out.println("cur tk: " + token.image + " " + token.kind);

        token = getNextToken();
    }
  }

  final public void HeaderSel() throws ParseException {
    T(HEADER_COMMENT);
}

  final public void IdentifierSel() throws ParseException {
    T(IDENTIFIER);
}

  final public void Define() throws ParseException {
    T(DEFINE);
    T(LBRACE);
    VariableBlock();
    T(RBRACE);
}

  final public void VariableBlock() throws ParseException {
    NotVariable();
    VariableSel1();
}

  final public void VariableSel1() throws ParseException {
    Variable();
}

  final public void VariableSel2() throws ParseException {
    NotVariable();
}

  final public void Execute() throws ParseException {
    T(EXECUTE);
    CommandBlock();
}

  final public void NotVariable() throws ParseException {
    T(NOT);
    T(VARIABLE);
    NotVariableDecl();
    NotVariableSel();
}

  final public void NotVariableSel() throws ParseException {
    NotVariableDecl();
    NotVariableSel();
}

  final public void NotVariableDecl() throws ParseException {
    Type();
    T(IS);
    IdentifierListValue();
}

  final public void IdentifierListValue() throws ParseException {
    T(IDENTIFIER);
    Value();
    IdentifierListValue1();
}

  final public void IdentifierListValue1() throws ParseException {
    T(COMMA);
    IdentifierListValue();
}

  final public void Variable() throws ParseException {
    T(VARIABLE);
    VariableDecl();
    VariableSel();
}

  final public void VariableSel() throws ParseException {
    VariableDecl();
    VariableSel();
}

  final public void VariableDecl() throws ParseException {
    Type();
    T(IS);
    IdentifierList();
    T(DOT);
}

  final public void IdentifierList() throws ParseException {
    T(IDENTIFIER);
    Index();
    IdentifierList1();
}

  final public void IdentifierList1() throws ParseException {
    T(COMMA);
    IdentifierList();
}

  final public void Set() throws ParseException {
    T(SET);
    Expression();
    T(TO);
    IdentifierList();
}

  final public void Get() throws ParseException {
    T(GET);
    T(LBRACE);
    IdentifierList();
    T(RBRACE);
}

  final public void Put() throws ParseException {
    T(PUT);
    T(LBRACE);
    PutList();
    T(RBRACE);
}

  final public void PutList() throws ParseException {
    IdentifierList();
}

  final public void Verify() throws ParseException {
    T(VERIFY);
    Expression();
    T(IS);
    FalseTrueSel();
}

  final public void FalseTrueSel() throws ParseException {
    TrueBlock();
    FalseTrueSel1();
}

  final public void FalseTrueSel1() throws ParseException {
    FalseBlock();
}

  final public void FalseTrueSel2() throws ParseException {
    TrueBlock();
}

  final public void TrueBlock() throws ParseException {
    T(TRUE);
    CommandBlock();
}

  final public void FalseBlock() throws ParseException {
    T(FALSE);
    CommandBlock();
}

  final public void Loop() throws ParseException {
    T(LOOP);
    CommandBlock();
    T(WHILE);
    Expression();
    T(IS);
    T(TRUE);
}

  final public void While() throws ParseException {
    T(WHILE);
    Expression();
    T(IS);
    T(TRUE);
    T(DO);
    CommandBlock();
}

  final public void CommandBlock() throws ParseException {
    T(LBRACE);
    Command();
    CommandList();
    T(RBRACE);
}

  final public void CommandList() throws ParseException {
    Command();
    CommandList();
}

  final public void Command() throws ParseException {
    CommandSel();
    T(DOT);
}

  final public void CommandSel() throws ParseException {
    Set();
}

  final public void Expression() throws ParseException {
    ExprArithLogic();
    ExpressionSel();
}

  final public void ExpressionSel() throws ParseException {
    T(EQUAL);
    ExprArithLogic();
}

  final public void ExprArithLogic() throws ParseException {
    Term2();
    LessPriority();
}

  final public void LessPriority() throws ParseException {
    T(PLUS);
    Term2();
    LessPriority();
}

  final public void Term2() throws ParseException {
    Term1();
    MidPriority();
}

  final public void MidPriority() throws ParseException {
    T(MULTIPLICATION);
    Term1();
    MidPriority();
}

  final public void Term1() throws ParseException {
    Element();
    GreatPriority();
}

  final public void GreatPriority() throws ParseException {
    T(POWER);
    Element();
    GreatPriority();
}

  final public void Element() throws ParseException {
    T(IDENTIFIER);
    Index();
}

  final public void Index() throws ParseException {
    T(LBRACKET);
    T(NATURAL_CONST);
    T(RBRACKET);
}

  final public void Value() throws ParseException {
    T(CHAR_CONST);
}

  final public void Type() throws ParseException {
    T(CHAR_TYPE);
}

  final public void Epsilon() throws ParseException {

}

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {};
	}

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[65];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 65; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
